[versions]
agp = "9.3.1"
foundation = "1.11.1"
kotlin = "2.4.10"
compose-multiplatform = "1.11.1"
coroutines = "1.11.0"
activity-compose = "1.13.0"
material = "1.14.0"
lifecycle = "2.11.0"
navigation = "2.9.2"
miuix = "0.9.3"
qrose = "1.1.2"
runtime = "1.11.1"
ui = "1.11.1"
bcrypt = "0.10.2"
quickie = "1.12.0"

[libraries]
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
miuix-ui = { module = "top.yukonga.miuix.kmp:miuix-ui", version.ref = "miuix" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons", version.ref = "miuix" }
miuix-preference = { module = "top.yukonga.miuix.kmp:miuix-preference", version.ref = "miuix" }
qrose = { group = "io.github.alexzhirkevich", name = "qrose", version.ref = "qrose" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "ui" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
quickie-bundled = { module = "io.github.g00fy2.quickie:quickie-bundled", version.ref = "quickie" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
